# Generated by Django 6.0.2 on 2026-05-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_notify_new_arrivals_profile_notify_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notified_categories',
            field=models.CharField(default='men,women,kids,toys', max_length=255),
        ),
    ]
