# Generated by Django 6.0.3 on 2026-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_siteupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('overall', 'Overall Experience'), ('delivery', 'Delivery Speed'), ('packaging', 'Packaging Quality'), ('support', 'Customer Support'), ('returns', 'Returns & Refunds')], default='overall', max_length=20)),
                ('delivery_rating', models.IntegerField(default=5)),
                ('packaging_rating', models.IntegerField(default=5)),
                ('support_rating', models.IntegerField(default=5)),
                ('returns_rating', models.IntegerField(default=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('comment', models.TextField()),
                ('is_verified_customer', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
