# Generated by Django 6.0.2 on 2026-05-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_ordertracking_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(blank=True, help_text='Selected color for cloth products', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Selected size for cloth products', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_extra_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional price for variant selection', max_digits=10),
        ),
    ]
