# Generated by Django 6.0.3 on 2026-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_cartitem_selected_color_cartitem_selected_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='colors_available',
            field=models.CharField(blank=True, default='', help_text='e.g. Red, Blue, Black', max_length=200),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='colors_available',
            field=models.CharField(blank=True, default='', help_text='e.g. Red, Blue, Black', max_length=200),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='sizes_available',
            field=models.CharField(blank=True, default='', help_text='e.g. S, M, L, XL', max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='colors_available',
            field=models.CharField(blank=True, default='', help_text='e.g. Red, Blue, Black', max_length=200),
        ),
        migrations.AddField(
            model_name='offers',
            name='sizes_available',
            field=models.CharField(blank=True, default='', help_text='e.g. S, M, L, XL', max_length=200),
        ),
        migrations.AddField(
            model_name='toy',
            name='colors_available',
            field=models.CharField(blank=True, default='', help_text='e.g. Red, Blue, Black', max_length=200),
        ),
        migrations.AddField(
            model_name='toy',
            name='sizes_available',
            field=models.CharField(blank=True, default='', help_text='e.g. S, M, L, XL', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant_extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
