# Generated by Django 6.0.2 on 2026-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_cloths_colors_available_newarrivals_colors_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='trending/')),
                ('price', models.CharField(max_length=50)),
                ('original_price', models.CharField(blank=True, max_length=50, null=True)),
                ('badge', models.CharField(blank=True, default='Trending', max_length=50)),
                ('category', models.CharField(choices=[('kids', 'Kids'), ('men', 'Men'), ('women', 'Women'), ('toys', 'Toys')], max_length=20)),
                ('link_url', models.CharField(help_text='Paste the full URL to the product detail page here', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trending Product',
                'verbose_name_plural': 'Trending Products',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
