# Generated by Django 6.0.2 on 2026-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_trendingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='exchange_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_size',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('card', 'Card Refund'), ('bank', 'Bank Transfer'), ('wallet', 'Store Wallet'), ('cash', 'Cash Refund')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.CharField(choices=[('wrong_size', 'Wrong size'), ('damaged', 'Damaged item'), ('wrong_product', 'Wrong product received'), ('defective', 'Defective toy'), ('quality', 'Quality issue'), ('changed_mind', 'Changed mind'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('received', 'Item Received'), ('completed', 'Refund/Exchange Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
