# Generated by Django 6.0.2 on 2026-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_return_exchange_color_return_exchange_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this product page was viewed'),
        ),
        migrations.AddField(
            model_name='newarrivals',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this product page was viewed'),
        ),
        migrations.AddField(
            model_name='offers',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this product page was viewed'),
        ),
        migrations.AddField(
            model_name='toy',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this product page was viewed'),
        ),
    ]
