# Generated by Django 6.0.2 on 2026-05-14 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_add_view_count_to_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingproduct',
            name='arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trending_entries', to='myapp.newarrivals'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='cloth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trending_entries', to='myapp.cloths'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trending_entries', to='myapp.offers'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='toy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trending_entries', to='myapp.toy'),
        ),
        migrations.AlterField(
            model_name='trendingproduct',
            name='link_url',
            field=models.CharField(blank=True, help_text='Optional legacy URL. Leave blank when using a product link below.', max_length=500),
        ),
    ]
