# Generated by Django 6.0.2 on 2026-05-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_trendingproduct_arrival_trendingproduct_cloth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.trendingproduct'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('toy', 'Toy'), ('cloth', 'Cloth'), ('offer', 'Offer'), ('arrival', 'New Arrival'), ('trending', 'Trending Product')], max_length=10),
        ),
    ]
