# Generated by Django 6.0.2 on 2026-05-14 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_cartitem_trending_alter_cartitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='trending',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='myapp.trendingproduct'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='myapp.trendingproduct'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='myapp.trendingproduct'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='care_instructions',
            field=models.TextField(blank=True, default='', help_text='Washing/Care instructions'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='colors_available',
            field=models.CharField(blank=True, default='', help_text='e.g. Red, Blue, Black', max_length=200),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='dimensions',
            field=models.CharField(blank=True, default='', help_text='e.g. 10x20x30 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Key features, one per line'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown on the product detail page'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. 100% Cotton, Polyester blend', max_length=200),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='safety_info',
            field=models.TextField(blank=True, default='', help_text='Safety warnings for toys'),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='sizes_available',
            field=models.CharField(blank=True, default='', help_text='e.g. S, M, L, XL', max_length=200),
        ),
        migrations.AddField(
            model_name='trendingproduct',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this product page was viewed'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_type',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('toy', 'Toy'), ('offer', 'Offer'), ('arrival', 'Arrival'), ('trending', 'Trending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_type',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('toy', 'Toy'), ('offer', 'Offer'), ('arrival', 'Arrival'), ('trending', 'Trending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product_type',
            field=models.CharField(choices=[('cloth', 'Cloth'), ('toy', 'Toy'), ('offer', 'Offer'), ('arrival', 'Arrival'), ('trending', 'Trending')], max_length=10),
        ),
    ]
