# Generated by Django 6.0.2 on 2026-05-14 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_inventory_trending_productimage_trending_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'cloth'), ('user', 'toy')},
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='myapp.newarrivals'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='myapp.offers'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='myapp.trendingproduct'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='item_type',
            field=models.CharField(choices=[('toy', 'Toy'), ('cloth', 'Cloth'), ('offer', 'Offer'), ('arrival', 'New Arrival'), ('trending', 'Trending Product')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'arrival'), ('user', 'cloth'), ('user', 'offer'), ('user', 'toy'), ('user', 'trending')},
        ),
    ]
