# Generated by Django 6.0.2 on 2026-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_order_loyalty_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprofile',
            name='gold_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiry date for Gold Tier', null=True),
        ),
    ]
